MYSQL_HOST="127.0.0.1"
MYSQL_PORT=3306
MYSQL_USER=isucon
MYSQL_DBNAME=isucondition
MYSQL_PASS=isucon
POST_ISUCONDITION_TARGET_BASE_URL="https://isucondition-2.t.isucon.dev"

# Shard1
MYSQL_HOST_SHARD1="127.0.0.1"
MYSQL_PORT_SHARD1=3306
MYSQL_USER_SHARD1=isucon
MYSQL_DBNAME_SHARD1=isucondition_shard1
MYSQL_PASS_SHARD1=isucon

# Shard2
MYSQL_HOST_SHARD2="127.0.0.1"
MYSQL_PORT_SHARD2=3306
MYSQL_USER_SHARD2=isucon
MYSQL_DBNAME_SHARD2=isucondition_shard2
MYSQL_PASS_SHARD2=isucon

# Shard3
MYSQL_HOST_SHARD3="127.0.0.1"
MYSQL_PORT_SHARD3=3306
MYSQL_USER_SHARD3=isucon
MYSQL_DBNAME_SHARD3=isucondition_shard3
MYSQL_PASS_SHARD3=isucon
